### ISSUE TITLE
Unable to install on ubuntu

### ISSUE THREAD

**Issue by janacm** [numerodix/spiderfetch#2]
Hi I'm getting this error when I try to install. 

 `Downloading/unpacking spiderfetch
  Downloading spiderfetch-0.4.9-py2.py3-none-any.whl
Downloading/unpacking ansicolor (from spiderfetch)
  Downloading ansicolor-0.2.4-py2.py3-none-any.whl
Installing collected packages: spiderfetch, ansicolor
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 671, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 901, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/spiderfetch-0.4.9.dist-info'

Storing debug log for failure in /home/speedbunty/.pip/pip.log
speedbunty@speedbunty-VirtualBox:~$`

**Comment by numerodix** [comment]
You are getting a permission error because you are trying to install spiderfetch system wide. For this you'll need root privileges, so either do this as root or under sudo: "sudo pip install spiderfetch".
